### ISSUE TITLE
找不到全局安装的命令

### ISSUE THREAD

**Issue by devbean** [version-fox/vfox-nodejs#11]
使用
```
vfox install nodejs
vfox use nodejs
```
后，全局安装 nodejs 依赖包：
```
npm install -g @angular/cli
```
使用`ng --version`会报错找不到命令。

使用`npm config get prefix`可以看到全局包被安装到了`current`目录。该目录应该加入环境变量，以便使用 npm 全局安装的命令。

**Comment by aooohan** [comment]
<img width="869" alt="image" src="https://github.com/version-fox/vfox-nodejs/assets/40265686/9a0a81d2-391f-4aa0-b7fd-fc4dbc08d6f9">

没有报错呀

> 被安装到了current目录。该目录应该加入环境变量，

加入path了, 你配置Hook了吗? 

https://vfox.lhan.me/zh-hans/guides/quick-start.html#_2-%E6%8C%82%E8%BD%BDvfox%E5%88%B0%E4%BD%A0%E7%9A%84shell

**Comment by devbean** [comment]
是说`ng --version`这个命令是报错的，您给出的截图也显示了红色的 Error。`npm config get prefix`返回的是`ng`命令被安装到了哪个目录。

**Comment by aooohan** [comment]
ng新版本用 ng v。😓

<img width="909" alt="image" src="https://github.com/version-fox/vfox-nodejs/assets/40265686/4e8c0a08-815b-41de-9e4a-343f36676581">

**Comment by devbean** [comment]
！
抱歉抱歉
