### ISSUE TITLE
Incorrect version sorting

### ISSUE THREAD

**Issue by colececil** [version-fox/vfox-nodejs#12]
In vfox v0.5.3 with nodejs plugin v0.3.0, when running `vfox list nodejs` or `vfox use nodejs`, some of the versions are sorted in the wrong order:

![image](https://github.com/version-fox/vfox-nodejs/assets/19720931/a3472fd9-2de3-4432-89a3-0b660709e9a3)

However, they are sorted correctly when running `vfox install nodejs`:

![image](https://github.com/version-fox/vfox-nodejs/assets/19720931/662bbf6b-4fa1-4eef-9189-19f33677c51d)

In case it's relevant, I'm running Git Bash on Windows 10.

**Comment by aooohan** [comment]
Please upgrade `vfox` to latest as fixed by https://github.com/version-fox/vfox/pull/285

**Comment by colececil** [comment]
Excellent - thank you! 🙌
